export enum StudentVerificationStatus {
  VERIFIED = "VERIFIED",
  NEED_VERIFICATION = "NEED_VERIFICATION",
  NOT_VERIFIED = "NOT_VERIFIED",
  EDUCATION_NOT_REGISTERED = "EDUCATION_NOT_REGISTERED",
}
