export enum PermissionName {
  BUSINESS_PROFILE_VIEW = 'perm:profile_completion:business_profile:view',
  BUSINESS_PROFILE_EDIT = 'perm:profile_completion:business_profile:edit',
  COMP_REP_VIEW = 'perm:profile_completion:comp_rep:view',
  COMP_REP_EDIT = 'perm:profile_completion:comp_rep:edit',
  HQ_BRANCH_INFO_VIEW = 'perm:profile_completion:hq_branch_info:view',
  HQ_BRANCH_INFO_EDIT = 'perm:profile_completion:hq_branch_info:edit',
  TEAM_MGMT_VIEW = 'perm:team_mgmt:view',
  TEAM_MGMT_EDIT = 'perm:team_mgmt:edit',
  EMPLOYEE_PERSONAL_VIEW = 'perm:employee_personal:view',
  EMPLOYEE_PERSONAL_EDIT = 'perm:employee_personal:edit',
  VIEW_PROFILE_SELF_PROFILE_VIEW = 'perm:view_profile:self_profile:view',
  VIEW_PROFILE_COMPANY_DETAILS_VIEW = 'perm:view_profile:company_details:view',
  VIEW_PROFILE_ORG_OVERVIEW_VIEW = 'perm:view_profile:org_overview:view',
  SELF_PROFILE_PERSONAL_EDIT = 'perm:self_profile:personal:edit',
  SELF_PROFILE_ROLE_EDIT = 'perm:self_profile:role:edit',
  HQ_REGISTER = 'perm:hq:register',
  HQ_EDIT = 'perm:hq:edit',
  BRANCH_REGISTER = 'perm:branch:register',
  BRANCH_EDIT = 'perm:branch:edit',
  TEAM_REGISTER = 'perm:team:register',
  TEAM_EDIT = 'perm:team:edit',
  OWNERSHIP_TRANSFER = 'perm:ownership:transfer',

  // Jobs
  JOBS_LIST_VIEW = 'perm:jobs:list:view',
  JOBS_DETAILS_VIEW = 'perm:jobs:details:view',
  JOBS_SAVED = 'perm:jobs:saved',
  JOBS_APPLIED = 'perm:jobs:applied',
  APPLICANT_VIEW = 'perm:applicant:view',
  JOB_CREATE_DETAILS = 'perm:job:create:details',
  JOB_CREATE_WORKFLOW = 'perm:job:create:workflow',
  JOB_CREATE_PUBLISH = 'perm:job:create:publish',
  JOB_DRAFT_EDIT = 'perm:job:draft:edit',
  JOB_CLOSE = 'perm:job:close',
}